---
title: "Untitled"
author: "Hoang-Chau Luong"
date: "6/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
library(lubridate)
library(gt)
library(dunnr)
extrafont::loadfonts(device = "win", quiet = TRUE)
theme_set(theme_td())
set_geom_fonts()
set_palette()
```

```{r}
tt <- tt_load("2021-05-18")

survey <- tt$survey

glimpse(survey)
skimr::skim(survey)
```

```{r}
# Convert character timestamp to a datetime object so we can plot it
survey <- survey %>%
  mutate(
    timestamp = lubridate::parse_date_time(timestamp, orders = "mdy HMS"),
    survey_date = as.Date(timestamp)
  )

survey %>%
  ggplot(aes(x = survey_date)) +
  geom_bar(fill = td_colors$nice$day9_yellow, alpha = 0.6) +
  scale_y_continuous(expand = expansion(c(0, 0.07))) +
  scale_x_date(breaks = seq.Date(as.Date("2021-05-01"),
                                 as.Date("2021-06-01"), by = "week")) +
  ggtitle("Over 10,000 responses in one day")
```

```{r}
survey %>%
  count(how_old_are_you) %>%
  gt()

survey <- survey %>%
  mutate(
    age_range = fct_reorder(
      how_old_are_you,
      parse_number(how_old_are_you)
    ) %>%
      fct_relevel("under 18")
  )

survey %>%
  ggplot(aes(y = age_range)) +
  geom_bar(aes(fill = age_range), show.legend = FALSE) +
  scale_fill_viridis_d() +
  scale_x_continuous(expand = expansion(c(0, 0.05)))
```

```{r}
survey %>%
  filter(age_range == "under 18") %>%
  select(industry, job_title, annual_salary, country,
         overall_years_of_professional_experience) %>%
  gt()
```

```{r}
survey %>%
  count(industry, sort = TRUE) %>%
  head(30) %>%
  mutate(rank = 1:n()) %>% relocate(rank) %>%
  gt() %>%
  tab_options(container.height = 300, container.overflow.y = TRUE)
```

```{r}
survey <- survey %>%
  mutate(
    industry_factor = fct_infreq(industry) %>%
      fct_lump_min(min = 100)
  )
  
survey %>%
  ggplot(aes(y = industry_factor)) +
  geom_bar(fill = td_colors$nice$indigo_blue) +
  scale_x_continuous(expand = c(0, 0))
```

```{r}
survey %>%
  count(job_title, sort = T) %>%
  head(50) %>%
  rmarkdown::paged_table()
```

```{r}
survey %>%
  filter(
    str_detect(job_title,
               regex("data|statistic|machine learn", ignore_case = TRUE))
  ) %>%
  count(job_title, sort = TRUE) %>%
  rmarkdown::paged_table()
```




















